remote_theme: pages-themes/minimal@v0.2.0

title: Panchami Baleri
description: Data Engineer | AWS | Spark | Tableau

author:
  name: Panchami Baleri
  email: panchami.baleri97@gmail.com
  github: Balerip
  linkedin: panchamibaleri

plugins:
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge
permalink: pretty

include:
  - assets

# Tell Jekyll to ignore the Minimal theme’s default layout
defaults:
  - scope:
      path: ""
    values:
      layout: default
