remote_theme: pages-themes/minimal@v0.2.0

title: Panchami Baleri
description: Data Engineer | AWS | Spark | Tableau

author:
  name: Panchami Baleri
  email: panchami.baleri97@gmail.com
  github: Balerip
  linkedin: panchamibaleri

plugins:
  - jekyll-remote-theme

social:
  github: https://github.com/Balerip
  linkedin: https://linkedin.com/in/panchamibaleri/
  email: panchami@example.com

markdown: kramdown
highlighter: rouge
permalink: pretty

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

